export const reverbIRs = {
  halls: {
    largeHall: '/src/assets/ir/reverb/1 Halls 01 Large Hall.wav',
    mediumHall: '/src/assets/ir/reverb/1 Halls 02 Medium Hall.wav',
    smallHall: '/src/assets/ir/reverb/1 Halls 03 Small Hall.wav',
    largeNear: '/src/assets/ir/reverb/1 Halls 04 Large & Near.wav',
    mediumNear: '/src/assets/ir/reverb/1 Halls 05 Medium & Near.wav',
    smallNear: '/src/assets/ir/reverb/1 Halls 06 Small & Near.wav',
    largeDark: '/src/assets/ir/reverb/1 Halls 07 Large & Dark.wav',
    largeDeep: '/src/assets/ir/reverb/1 Halls 08 Large & Deep.wav',
    mediumDeep: '/src/assets/ir/reverb/1 Halls 09 Medium & Deep.wav',
    concertHall: '/src/assets/ir/reverb/1 Halls 10 Concert Hall.wav',
    goldHall: '/src/assets/ir/reverb/1 Halls 11 Gold Hall.wav',
    sandorsHall: '/src/assets/ir/reverb/1 Halls 12 Sandors Hall.wav',
    denseHall: '/src/assets/ir/reverb/1 Halls 13 Dense Hall.wav',
    clearHall: '/src/assets/ir/reverb/1 Halls 14 Clear Hall.wav',
    brassHall: '/src/assets/ir/reverb/1 Halls 15 Brass Hall.wav',
    amsterdamHall: '/src/assets/ir/reverb/1 Halls 16 Amsterdam Hall.wav',
    berlinerHall: '/src/assets/ir/reverb/1 Halls 17 Berliner Hall.wav',
    bostonHallA: '/src/assets/ir/reverb/1 Halls 18 Boston Hall A.wav',
    bostonHallB: '/src/assets/ir/reverb/1 Halls 19 Boston Hall B.wav',
    chicagoHall: '/src/assets/ir/reverb/1 Halls 20 Chicago Hall.wav',
    viennaHall: '/src/assets/ir/reverb/1 Halls 21 Vienna Hall.wav',
    worcesterHall: '/src/assets/ir/reverb/1 Halls 22 Worcester Hall.wav',
    theArchDuke: '/src/assets/ir/reverb/1 Halls 23 The ArchDuke.wav',
    troyMusicHall: '/src/assets/ir/reverb/1 Halls 24 Troy Music Hall.wav',
    saintSylvain: '/src/assets/ir/reverb/1 Halls 25 Saint Sylvain.wav',
    mechanicsHall: '/src/assets/ir/reverb/1 Halls 26 Mechanics Hall.wav',
    saintGerold: '/src/assets/ir/reverb/1 Halls 27 Saint Gerold.wav',
  },
  plates: {
    brightPlate: '/src/assets/ir/reverb/2 Plates 01 Bright Plate',
    darkPlate: '/src/assets/ir/reverb/2 Plates 02 Dark Plate.wav',
    londonPlate: '/src/assets/ir/reverb/2 Plates 03 London Plate.wav',
    snarePlateA: '/src/assets/ir/reverb/2 Plates 04 Snare Plate A.wav',
    snarePlateB: '/src/assets/ir/reverb/2 Plates 05 Snare Plate B.wav',
    vocalPlate: '/src/assets/ir/reverb/2 Plates 06 Vocal Plate.wav',
    oldPlate: '/src/assets/ir/reverb/2 Plates 07 Old Plate.wav',
    richPlate: '/src/assets/ir/reverb/2 Plates 08 Rich Plate.wav',
    goldPlate: '/src/assets/ir/reverb/2 Plates 09 Gold Plate.wav',
    densePlate: '/src/assets/ir/reverb/2 Plates 10 Dense Plate.wav',
    silverPlate: '/src/assets/ir/reverb/2 Plates 11 Silver Plate.wav',
    percussionPlate: '/src/assets/ir/reverb/2 Plates 12 Percussion Plate.wav',
    echoPlate: '/src/assets/ir/reverb/2 Plates 13 Echo Plate.wav',
    cdPlateA: '/src/assets/ir/reverb/2 Plates 14 CD Plate A.wav',
    cdPlateB: '/src/assets/ir/reverb/2 Plates 15 CD Plate B.wav',
    largePlate: '/src/assets/ir/reverb/2 Plates 16 Large Plate.wav',
    smallPlate: '/src/assets/ir/reverb/2 Plates 17 Small Plate.wav',
    fatPlate: '/src/assets/ir/reverb/2 Plates 18 fat Plate.wav',
    crystalPlate: '/src/assets/ir/reverb/2 Plates 19 crystal Plate.wav',
    sunPlateA: '/src/assets/ir/reverb/2 Plates 20 Sun Plate A.wav',
    sunPlateB: '/src/assets/ir/reverb/2 Plates 21 Sun Plate B.wav',
    sunPlateC: '/src/assets/ir/reverb/2 Plates 22 Sun Plate C.wav',
    vocalPlateB: '/src/assets/ir/reverb/2 Plates 23 Vocal Plate B.wav',
  },
  rooms: {
    studioA: '/src/assets/ir/reverb/3 Rooms 01 Studio A.wav',
    studioBClose: '/src/assets/ir/reverb/3 Rooms 02 Studio B Close.wav',
    studioBFar: '/src/assets/ir/reverb/3 Rooms 03 Studio B Far.wav',
    studioC: '/src/assets/ir/reverb/3 Rooms 04 Studio C.wav',
    studioD: '/src/assets/ir/reverb/3 Rooms 05 Studio D.wav',
    studioE: '/src/assets/ir/reverb/3 Rooms 06 Studio E.wav',
    deepStone: '/src/assets/ir/reverb/3 Rooms 07 Deep Stone.wav',
    musicRoom: '/src/assets/ir/reverb/3 Rooms 08 Music Room.wav',
    heavyRoom: '/src/assets/ir/reverb/3 Rooms 09 Heavy Room.wav',
    largeWoodenRoom: '/src/assets/ir/reverb/3 Rooms 10 Large Wooden Room.wav',
    smallWoodenRoom: '/src/assets/ir/reverb/3 Rooms 11 Small Wooden Room.wav',
    largeTiledRoom: '/src/assets/ir/reverb/3 Rooms 12 Large Tiled Room.wav',
    mediumTiledRoom: '/src/assets/ir/reverb/3 Rooms 13 Medium Tiled Room.wav',
    smallTiledRoom: '/src/assets/ir/reverb/3 Rooms 14 Small Tiled Room.wav',
    drumAndChamber: '/src/assets/ir/reverb/3 Rooms 15 Drum & Chamber.wav',
    djangosRoom: '/src/assets/ir/reverb/3 Rooms 16 Djangos Room.wav',
    smallVoxRoom: '/src/assets/ir/reverb/3 Rooms 17 Small Vox Room.wav',
    glassRoom: '/src/assets/ir/reverb/3 Rooms 18 Glass Room.wav',
    percussionRoom: '/src/assets/ir/reverb/3 Rooms 19 Percussion Room.wav',
    marbleFoyer: '/src/assets/ir/reverb/3 Rooms 20 Marble Foyer.wav',
    largeAndRoom: '/src/assets/ir/reverb/3 Rooms 21 Large & Room.wav',
    smallAndRoom: '/src/assets/ir/reverb/3 Rooms 22 Small & Room.wav',
    largeRedRoom: '/src/assets/ir/reverb/3 Rooms 23 Large Red Room.wav',
    redRoom: '/src/assets/ir/reverb/3 Rooms 24 Red Room.wav',
    blueRoom: '/src/assets/ir/reverb/3 Rooms 25 Blue Room.wav',
    largeRoom: '/src/assets/ir/reverb/3 Rooms 26 Large Room.wav',
    smallRoom: '/src/assets/ir/reverb/3 Rooms 27 Small Room.wav',
    frontRoom: '/src/assets/ir/reverb/3 Rooms 28 Front Room.wav',
    centerRoom: '/src/assets/ir/reverb/3 Rooms 29 Center Room.wav',
    backRoom: '/src/assets/ir/reverb/3 Rooms 30 Back Room.wav',
    studioK: '/src/assets/ir/reverb/3 Rooms 31 Studio K.wav',
    waitsRoom: '/src/assets/ir/reverb/3 Rooms 32 Waits Room.wav',
    cornRoom: '/src/assets/ir/reverb/3 Rooms 33 Corn Room.wav',
    oaklandRoom: '/src/assets/ir/reverb/3 Rooms 34 Oakland Room.wav',
    sfPerfRoom: '/src/assets/ir/reverb/3 Rooms 35 SF Perf Room.wav',
  },
  chambers: {
    largeChamber: '/src/assets/ir/reverb/4 Chambers 01 Large Chamber.wav',
    mediumChamber: '/src/assets/ir/reverb/4 Chambers 02 Medium Chamber.wav',
    smallChamber: '/src/assets/ir/reverb/4 Chambers 03 Small Chamber.wav',
    largeAndDark: '/src/assets/ir/reverb/4 Chambers 04 Large & Dark.wav',
    smallAndDark: '/src/assets/ir/reverb/4 Chambers 05 Small & Dark.wav',
    largeAndBright: '/src/assets/ir/reverb/4 Chambers 06 Large & Bright.wav',
    smallAndBright: '/src/assets/ir/reverb/4 Chambers 07 Small & Bright.wav',
    kickChamber: '/src/assets/ir/reverb/4 Chambers 08 Kick Chamber.wav',
    snareChamber: '/src/assets/ir/reverb/4 Chambers 09 Snare Chamber.wav',
    vocalChamber: '/src/assets/ir/reverb/4 Chambers 10 Vocal Chamber.wav',
    aAndM: '/src/assets/ir/reverb/4 Chambers 11 A&M Chamber.wav',
    cdChamber: '/src/assets/ir/reverb/4 Chambers 12 CD Chamber.wav',
    oldChamber: '/src/assets/ir/reverb/4 Chambers 13 Old Chamber.wav',
    deepChamber: '/src/assets/ir/reverb/4 Chambers 14 Deep Chamber.wav',
    ambChamberA: '/src/assets/ir/reverb/4 Chambers 15 Amb Chamber A.wav',
    ambChamberB: '/src/assets/ir/reverb/4 Chambers 16 Amb Chamber B.wav',
    sunsetChamber: '/src/assets/ir/reverb/4 Chambers 17 Sunset Chamber.wav',
  },
  ambiences: {},
  spaces: {},
}
