export const reverbIRs = {
  halls: {
    largeHall: '/src/assets/ir/reverb/1 Halls 01 Large Hall.wav',
    mediumHall: '/src/assets/ir/reverb/1 Halls 02 Medium Hall.wav',
    smallHall: '/src/assets/ir/reverb/1 Halls 03 Small Hall.wav',
    largeNear: '/src/assets/ir/reverb/1 Halls 04 Large & Near.wav',
    mediumNear: '/src/assets/ir/reverb/1 Halls 05 Medium & Near.wav',
    smallNear: '/src/assets/ir/reverb/1 Halls 06 Small & Near.wav',
    largeDark: '/src/assets/ir/reverb/1 Halls 07 Large & Dark.wav',
    largeDeep: '/src/assets/ir/reverb/1 Halls 08 Large & Deep.wav',
    mediumDeep: '/src/assets/ir/reverb/1 Halls 09 Medium & Deep.wav',
    concertHall: '/src/assets/ir/reverb/1 Halls 10 Concert Hall.wav',
    goldHall: '/src/assets/ir/reverb/1 Halls 11 Gold Hall.wav',
    sandorsHall: '/src/assets/ir/reverb/1 Halls 12 Sandors Hall.wav',
    denseHall: '/src/assets/ir/reverb/1 Halls 13 Dense Hall.wav',
    clearHall: '/src/assets/ir/reverb/1 Halls 14 Clear Hall.wav',
    brassHall: '/src/assets/ir/reverb/1 Halls 15 Brass Hall.wav',
    amsterdamHall: '/src/assets/ir/reverb/1 Halls 16 Amsterdam Hall.wav',
    berlinerHall: '/src/assets/ir/reverb/1 Halls 17 Berliner Hall.wav',
    bostonHallA: '/src/assets/ir/reverb/1 Halls 18 Boston Hall A.wav',
    bostonHallB: '/src/assets/ir/reverb/1 Halls 19 Boston Hall B.wav',
    chicagoHall: '/src/assets/ir/reverb/1 Halls 20 Chicago Hall.wav',
    viennaHall: '/src/assets/ir/reverb/1 Halls 21 Vienna Hall.wav',
    worcesterHall: '/src/assets/ir/reverb/1 Halls 22 Worcester Hall.wav',
    theArchDuke: '/src/assets/ir/reverb/1 Halls 23 The ArchDuke.wav',
    troyMusicHall: '/src/assets/ir/reverb/1 Halls 24 Troy Music Hall.wav',
    saintSylvain: '/src/assets/ir/reverb/1 Halls 25 Saint Sylvain.wav',
    mechanicsHall: '/src/assets/ir/reverb/1 Halls 26 Mechanics Hall.wav',
    saintGerold: '/src/assets/ir/reverb/1 Halls 27 Saint Gerold.wav',
  },
  plates: {},
  rooms: {},
  chambers: {},
  ambiences: {},
  spaces: {},
}
